// <copyright file="Program.cs" company="MSanyi">
// Copyright (c) MSanyi.All rights reserved.
// </copyright>

namespace Vegyesbolt.MVC
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.Hosting;
    using Microsoft.Extensions.Logging;

    /// <summary>
    /// The autogenarated class.
    /// Magic is happening here.
    /// Autogenerated magic.
    /// </summary>
    public static class Program
    {
        /// <summary>
        /// Some real magic.
        /// </summary>
        /// <param name="args">Well might use it, but not really.</param>
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        /// <summary>
        /// Some real magic starting the webApp.
        /// </summary>
        /// <param name="args">As steted some args, that might get used.</param>
        /// <returns>Well the app we run.</returns>
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
