var dir_a010a2f2eba5f4195989424033db4339 =
[
    [ "AutoGeneratedModels", "dir_706e20c59950cd5c621466c43e9dc408.html", "dir_706e20c59950cd5c621466c43e9dc408" ],
    [ "Context", "dir_cf714bd6a85cdedc3eb5a5fb9685a7cc.html", "dir_cf714bd6a85cdedc3eb5a5fb9685a7cc" ],
    [ "Model", "dir_1bb8530a7659ee73b689db0f13af3b67.html", "dir_1bb8530a7659ee73b689db0f13af3b67" ],
    [ "obj", "dir_68cb41a1729a713e779866c5dfb84e8a.html", "dir_68cb41a1729a713e779866c5dfb84e8a" ],
    [ "GlobalSuppressions.cs", "_vegyes_bolt_8_data_2_global_suppressions_8cs_source.html", null ]
];