var dir_e67d1396ddb65d6c58ed05f582b2fed2 =
[
    [ "AutoGeneratedModels", "dir_09f3f16f5ad324b3674fa3bdbada1ed9.html", "dir_09f3f16f5ad324b3674fa3bdbada1ed9" ],
    [ "Context", "dir_1621b022e59bcf573935d603a56478c7.html", "dir_1621b022e59bcf573935d603a56478c7" ],
    [ "Model", "dir_bc61286b65dc1db8a404b1f58affc690.html", "dir_bc61286b65dc1db8a404b1f58affc690" ],
    [ "obj", "dir_1b39e47e886de26476a4437f07ec3bb5.html", "dir_1b39e47e886de26476a4437f07ec3bb5" ],
    [ "GlobalSuppressions.cs", "_vegyes_bolt_8_data_2_global_suppressions_8cs_source.html", null ]
];