//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

#nullable disable

namespace VegyesBolt.Data
{
    public partial class Vasarlok
    {
        public Vasarlok()
        {
            Vasarlasoks = new HashSet<Vasarlasok>();
        }

        public double Id { get; set; }
        public string Nev { get; set; }
        public string Email { get; set; }
        public DateTime RegDate { get; set; }
        public double? Megye { get; set; }

        public virtual Megyek MegyeNavigation { get; set; }
        public virtual ICollection<Vasarlasok> Vasarlasoks { get; set; }
    }
}

