//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;

#nullable disable

namespace VegyesBolt.Data
{
    public partial class Termekek
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="Termekek"/> class.
        /// </summary>
        public Termekek()
        {
            Vasarlasoks = new HashSet<Vasarlasok>();
        }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public double Id { get; set; }
        
        /// <summary>
        /// Autogenerated.
        /// </summary>
        public string TermekNeve { get; set; }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public double? Ara { get; set; }
       
        /// <summary>
        /// Autogenerated.
        /// </summary>
        public double? AfasAra { get; set; }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public int? LeltarMennyiseg { get; set; }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public virtual ICollection<Vasarlasok> Vasarlasoks { get; set; }
    }
    
}

