//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

#nullable disable

namespace VegyesBolt.Data
{
    public partial class Vasarlok
    {
        /// <summary>
        /// Autogenerated.
        /// </summary>
        public Vasarlok()
        {
            Vasarlasoks = new HashSet<Vasarlasok>();
        }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public double Id { get; set; }
        
        /// <summary>
        /// Autogenerated.
        /// </summary>
        public string Nev { get; set; }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public DateTime RegDate { get; set; }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public double? Megye { get; set; }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public virtual Megyek MegyeNavigation { get; set; }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public virtual ICollection<Vasarlasok> Vasarlasoks { get; set; }
    }
}

