//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

#nullable disable

namespace VegyesBolt.Data
{
    public partial class Vasarlasok
    {
        /// <summary>
        /// Autogenerated.
        /// </summary>
        public double VasarloId { get; set; }
        
        /// <summary>
        /// Autogenerated.
        /// </summary>
        public double TermekId { get; set; }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public DateTime VasarlasDatuma { get; set; }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public double? Mennyiseg { get; set; }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public virtual Termekek Termek { get; set; }

        /// <summary>
        /// Autogenerated.
        /// </summary>
        public virtual Vasarlok Vasarlo { get; set; }
    }
}
